### ISSUE TITLE
为什么QQ小程序也是使用这个脚手架

### ISSUE THREAD

**Issue by wuweikd** [wechat-miniprogram/miniprogram-cli#4]
在QQ官方文档中，https://q.qq.com/wiki/develop/miniprogram/frame/diy_components/diy_components_extend_3.html

指出也是使用此脚手架构建，但是构建时候并没有选择是QQ小程序还是微信小程序。

**Comment by JuneAndGreen** [comment]
这个。。。其实他们并没有跟我们沟通过会用这个，所以这个其实一开始就是为微信小程序实现的。也许是他们的文档没有更新吧。。。
