### ISSUE TITLE
组件是否支持 web-view 标签呢？

### ISSUE THREAD

**Issue by roy-lau** [wechat-miniprogram/miniprogram-cli#9]
您好，

请教您个问题：第三方自定义组件 https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/trdparty.html，内是否支持 web-view https://developers.weixin.qq.com/miniprogram/dev/component/web-view.html 标签呢？

**Comment by JuneAndGreen** [comment]
支持，他就是小程序的自定义组件。

不过我建议用 [mpflow](https://wechat-miniprogram.github.io/mpflow/docs/)，他的工具库更全面一些

**Comment by roy-lau** [comment]
好的，感谢回复。我会看看的

> 支持，他就是小程序的自定义组件。
> 
> 不过我建议用 [mpflow](https://wechat-miniprogram.github.io/mpflow/docs/)，他的工具库更全面一些
